---
- name: become root and deploy sshtun service
  import_tasks: root.yml
  become: true
  when: srv_sshtun_ssh_user |default('')
  tags: srv_sshtun_all

- name: run handlers now
  meta: flush_handlers
...
